version: '3'

services:
  db:
    image: mysql:5.7
    command:
      - --innodb-use-native-aio=0
    container_name: db
    restart: unless-stopped # evitar execução ao ligar o computador
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=node-db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 2s
      timeout: 10s
      retries: 10

  app:
    container_name: app
    build:
      context: ./node
    networks:
      - node-network
    depends_on:
      db:
        condition: service_healthy

  proxy:
    container_name: proxy
    build:
      context: ./nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy

networks:
  node-network:
    driver: bridge

volumes:
  db:
